version: '3.8'

volumes:
  mongodb_data:
    driver: local

services:
  backend:
    build: .
    container_name: lite_llm_adapter
    env_file:
      - .env
    environment:
      # Override the REDIS_URL from the .env file for the Docker environment.
      # Inside Docker Compose, services can reach each other using their service name.
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      # Mount the local models directory into the container
      # This avoids including large model files in the image.
      - ./models/gguf_models:/app/models/gguf_models
      # For development, mount the config files to allow changes without rebuilding.
      - ./models/model_config_dev.json:/app/models/model_config_dev.json:ro
      # - ./models/model_config_prod.json:/app/models/model_config_prod.json:ro
      - ./models/model_config_defaults.json:/app/models/model_config_defaults.json:ro
    # For serving LLMs, it's best to use a single worker to avoid duplicating models in memory.
    # Concurrency is handled inside the app with asyncio and the concurrency_manager.
    # We use Gunicorn as a process manager for Uvicorn workers for production-grade stability.
    # -k uvicorn.workers.UvicornWorker: Use Uvicorn's high-performance worker class.
    # -w 1: Use a single worker to avoid duplicating the LLM in memory.
    # --timeout 600: Use a long timeout (10 minutes) to handle slow model loading and long inference tasks.
    # --bind 0.0.0.0:8000: Bind to the correct host and port.
    command: gunicorn -k uvicorn.workers.UvicornWorker -w 1 --timeout 600 --pythonpath /app main:app --bind 0.0.0.0:8000
    depends_on:
      redis:
        condition: service_healthy
    # This healthcheck curls the app's own /health endpoint to ensure it's running.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis", "--raw", "ping"]
      interval: 1s
      timeout: 60s
      retries: 30
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    ports:
      - "3080:3080"
    env_file:
      - librechat.env
    depends_on:
      mongodb:
        condition: service_healthy
      backend:
        condition: service_healthy
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
    restart: unless-stopped
